//
//  ScheduledWorkout.swift
//  gym app
//
//  A scheduled workout or rest day for a specific date
//

import Foundation

struct ScheduledWorkout: Identifiable, Codable, Hashable {
    var id: UUID
    var workoutId: UUID?  // nil for rest days
    var workoutName: String  // "Rest" for rest days
    var scheduledDate: Date
    var completedSessionId: UUID?  // Links to session if completed
    var isRestDay: Bool
    var notes: String?
    var createdAt: Date

    // Program tracking fields
    var programId: UUID?       // Which program generated this (nil if manual)
    var programSlotId: UUID?   // Which slot it came from

    /// Initialize a scheduled workout
    init(
        id: UUID = UUID(),
        workoutId: UUID,
        workoutName: String,
        scheduledDate: Date,
        completedSessionId: UUID? = nil,
        notes: String? = nil,
        createdAt: Date = Date(),
        programId: UUID? = nil,
        programSlotId: UUID? = nil
    ) {
        self.id = id
        self.workoutId = workoutId
        self.workoutName = workoutName
        self.scheduledDate = scheduledDate
        self.completedSessionId = completedSessionId
        self.isRestDay = false
        self.notes = notes
        self.createdAt = createdAt
        self.programId = programId
        self.programSlotId = programSlotId
    }

    /// Initialize a rest day
    init(
        id: UUID = UUID(),
        scheduledDate: Date,
        notes: String? = nil,
        createdAt: Date = Date()
    ) {
        self.id = id
        self.workoutId = nil
        self.workoutName = "Rest"
        self.scheduledDate = scheduledDate
        self.completedSessionId = nil
        self.isRestDay = true
        self.notes = notes
        self.createdAt = createdAt
        self.programId = nil
        self.programSlotId = nil
    }

    // Custom decoder to handle missing fields from older Firebase documents
    init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        id = try container.decode(UUID.self, forKey: .id)
        workoutId = try container.decodeIfPresent(UUID.self, forKey: .workoutId)
        workoutName = try container.decodeIfPresent(String.self, forKey: .workoutName) ?? "Unknown"
        scheduledDate = try container.decode(Date.self, forKey: .scheduledDate)
        completedSessionId = try container.decodeIfPresent(UUID.self, forKey: .completedSessionId)
        isRestDay = try container.decodeIfPresent(Bool.self, forKey: .isRestDay) ?? (workoutId == nil)
        notes = try container.decodeIfPresent(String.self, forKey: .notes)
        createdAt = try container.decodeIfPresent(Date.self, forKey: .createdAt) ?? Date()
        programId = try container.decodeIfPresent(UUID.self, forKey: .programId)
        programSlotId = try container.decodeIfPresent(UUID.self, forKey: .programSlotId)
    }

    private enum CodingKeys: String, CodingKey {
        case id, workoutId, workoutName, scheduledDate, completedSessionId, isRestDay, notes, createdAt, programId, programSlotId
    }

    var isCompleted: Bool {
        completedSessionId != nil || isRestDay
    }

    /// Whether this scheduled workout was generated by a program
    var isFromProgram: Bool {
        programId != nil
    }

    /// Check if this scheduled workout is for a specific date (ignoring time)
    func isScheduledFor(date: Date) -> Bool {
        Calendar.current.isDate(scheduledDate, inSameDayAs: date)
    }
}
