//
//  ProgramViewModel.swift
//  gym app
//
//  ViewModel for managing training programs
//

import Foundation
import Combine

@MainActor
class ProgramViewModel: ObservableObject {
    @Published var programs: [Program] = []
    @Published var activeProgram: Program?
    @Published var isLoading = false
    @Published var errorMessage: String?

    private let repository: DataRepository
    private let workoutViewModel: WorkoutViewModel

    init(repository: DataRepository? = nil, workoutViewModel: WorkoutViewModel) {
        self.repository = repository ?? DataRepository.shared
        self.workoutViewModel = workoutViewModel
        loadPrograms()
    }

    // MARK: - Load Programs

    func loadPrograms() {
        isLoading = true
        repository.loadPrograms()
        programs = repository.programs
        activeProgram = programs.first { $0.isActive }
        isLoading = false
    }

    // MARK: - Program CRUD

    func createProgram(name: String, durationWeeks: Int = 4, description: String? = nil) -> Program {
        let program = Program(
            name: name,
            programDescription: description,
            durationWeeks: durationWeeks
        )
        saveProgram(program)
        return program
    }

    func saveProgram(_ program: Program) {
        var updatedProgram = program
        updatedProgram.updatedAt = Date()
        repository.saveProgram(updatedProgram)
        loadPrograms()
    }

    func deleteProgram(_ program: Program) {
        // If this program is active, deactivate it first
        if program.isActive {
            deactivateProgram(program, removeFutureScheduled: true)
        }
        repository.deleteProgram(program)
        loadPrograms()
    }

    func getProgram(id: UUID) -> Program? {
        programs.first { $0.id == id }
    }

    // MARK: - Workout Slot Management

    func addWorkoutSlot(
        to program: Program,
        workoutId: UUID,
        workoutName: String,
        dayOfWeek: Int,
        scheduleType: SlotScheduleType = .weekly,
        weekNumber: Int? = nil
    ) {
        var updatedProgram = program

        let existingSlotsForDay = program.workoutSlots.filter {
            $0.dayOfWeek == dayOfWeek &&
            ($0.scheduleType == .weekly || $0.weekNumber == weekNumber)
        }
        let newOrder = existingSlotsForDay.count

        let slot = ProgramWorkoutSlot(
            workoutId: workoutId,
            workoutName: workoutName,
            scheduleType: scheduleType,
            dayOfWeek: dayOfWeek,
            weekNumber: weekNumber,
            order: newOrder
        )

        updatedProgram.addSlot(slot)
        saveProgram(updatedProgram)
    }

    func removeWorkoutSlot(_ slotId: UUID, from program: Program) {
        var updatedProgram = program
        updatedProgram.removeSlot(slotId)
        saveProgram(updatedProgram)
    }

    func updateWorkoutSlot(_ slot: ProgramWorkoutSlot, in program: Program) {
        var updatedProgram = program
        updatedProgram.updateSlot(slot)
        saveProgram(updatedProgram)
    }

    // MARK: - Program Activation

    /// Activate a program starting from a given date
    /// This generates ScheduledWorkouts for the entire program duration
    func activateProgram(_ program: Program, startDate: Date) {
        // First, deactivate any currently active program
        if let current = activeProgram, current.id != program.id {
            deactivateProgram(current, removeFutureScheduled: false)
        }

        // Update program with start date and active flag
        var updatedProgram = program
        updatedProgram.startDate = startDate
        updatedProgram.endDate = updatedProgram.computedEndDate
        updatedProgram.isActive = true
        updatedProgram.updatedAt = Date()

        // Generate scheduled workouts
        let scheduledWorkouts = updatedProgram.generateScheduledWorkouts(from: startDate)

        // Add each scheduled workout via WorkoutViewModel
        for scheduled in scheduledWorkouts {
            workoutViewModel.addScheduledWorkout(scheduled)
        }

        repository.saveProgram(updatedProgram)
        loadPrograms()
    }

    /// Deactivate a program
    /// Optionally removes future scheduled workouts generated by this program
    func deactivateProgram(_ program: Program, removeFutureScheduled: Bool) {
        var updatedProgram = program
        updatedProgram.isActive = false
        updatedProgram.updatedAt = Date()

        if removeFutureScheduled {
            workoutViewModel.removeScheduledWorkoutsForProgram(program.id, futureOnly: true)
        }

        repository.saveProgram(updatedProgram)
        loadPrograms()
    }

    /// Handle program modification while active
    /// Returns the scheduled workouts that would be affected
    func previewProgramChanges(_ program: Program) -> [ScheduledWorkout] {
        guard program.isActive, let startDate = program.startDate else {
            return []
        }

        // Get what the new schedule would look like
        let newScheduled = program.generateScheduledWorkouts(from: startDate)

        // Filter to future dates only
        let today = Calendar.current.startOfDay(for: Date())
        return newScheduled.filter { $0.scheduledDate >= today }
    }

    /// Update an active program's future scheduled workouts
    func updateActiveProgramSchedule(_ program: Program) {
        guard program.isActive, let startDate = program.startDate else { return }

        // Remove future scheduled workouts for this program
        workoutViewModel.removeScheduledWorkoutsForProgram(program.id, futureOnly: true)

        // Regenerate from today onwards
        let today = Calendar.current.startOfDay(for: Date())
        let scheduledWorkouts = program.generateScheduledWorkouts(from: startDate)
            .filter { $0.scheduledDate >= today }

        // Add the new scheduled workouts
        for scheduled in scheduledWorkouts {
            workoutViewModel.addScheduledWorkout(scheduled)
        }
    }

    // MARK: - Computed Properties

    /// Get the number of workouts per week for a program
    func workoutsPerWeek(for program: Program) -> Int {
        let weeklySlots = program.workoutSlots.filter { $0.scheduleType == .weekly }
        return weeklySlots.count
    }

    /// Get unique days with workouts in a program's weekly template
    func workoutDays(for program: Program) -> [Int] {
        let weeklySlots = program.workoutSlots.filter { $0.scheduleType == .weekly }
        let days = Set(weeklySlots.compactMap { $0.dayOfWeek })
        return days.sorted()
    }
}
